controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: fake_gripper_tool_controller
    type: $(arg execution_type)
    joints:
      - finger_left_joint
initial:  # Define initial robot poses.
  - group: manipulator
    pose: home
  - group: gripper_tool
    pose: gripper_open