controller_list:
  - name: fake_camera_controller
    type: $(arg execution_type)
    joints:
      []
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger_left_joint
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: gripper
    pose: open
  - group: arm
    pose: random